;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-pound
        clm:web-page-title-at-point
        clm:yt-title-at-point
        comment-line
        counsel-M-x
        counsel-yank-pop
        end-of-visual-line
        eval-last-sexp
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        kill-visual-line
        markdown-outdent-or-delete
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-kill-line
        org-metaleft
        org-open-at-point
        org-return-indent
        org-self-insert-command
        org-yank
        overwrite-mode
        py-electric-colon
        py-electric-comment
        swiper
        yaml-electric-dash-and-dot
        beginning-of-visual-line
        hungry-delete-backward
        query-replace
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ))
