;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        clm:web-page-title-at-point
        clm:yt-title-at-point
        counsel-M-x
        counsel-yank-pop
        downcase-region
        end-of-visual-line
        hungry-delete-backward
        hungry-delete-forward
        ido-switch-buffer
        indent-for-tab-command
        kill-region
        kill-visual-line
        markdown-cycle
        markdown-outdent-or-delete
        org-beginning-of-line
        org-end-of-line
        org-force-cycle-archived
        org-kill-line
        org-open-at-point
        org-open-line
        org-return-indent
        org-self-insert-command
        org-yank
        py-electric-colon
        py-electric-comment
        py-indent-or-complete
        swiper
        text-scale-decrease
        text-scale-increase
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        py-hungry-delete-backwards
        yaml-electric-backspace
        ))
